version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:3.6.6-management
    ports:
      - 5672:5672
      - 15672:15672

  user:
    image: user-ms
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - ./src:/usr/local/user-ms/src
      - ./package.json:/usr/local/user-ms/package.json
      - ./package-lock.json:/usr/local/user-ms/package-lock.json
      - ./tsconfig.json:/usr/local/user-ms/tsconfig.json
      - ./config:/usr/local/user-ms/config
    depends_on:
      - rabbitmq
    ports:
      - 3000:3000
